// Definir las opciones para los selects
export const Ocupaciones: string[] = [
    'Abogado',
    'Actor/Actriz',
    'Agricultor/a',
    'Arqueólogo/a',
    'Arquitecto',
    'Artista Visual',
    'Asesor/a Financiero/a',
    'Asistente Administrativo',
    'Biólogo/a',
    'Carpintero',
    'Chef',
    'Contador',
    'Dentista',
    'Diseñador/a de Moda',
    'Diseñador Gráfico',
    'Economista',
    'Editor/a',
    'Educador/a Social',
    'Electricista',
    'Enfermero/a',
    'Escritor/a',
    'Farmacéutico/a',
    'Fotógrafo/a',
    'Geólogo/a',
    'Ingeniero/a Agrónomo/a',
    'Ingeniero/a Civil',
    'Ingeniero/a de Sistemas',
    'Ingeniero/a Ambiental',
    'Juez/a',
    'Médico/a General',
    'Médico/a Especialista',
    'Meteorólogo/a',
    'Nutricionista',
    'Periodista',
    'Piloto/a',
    'Programador/a Frontend',
    'Programador/a Backend',
    'Psicólogo/a Clínico',
    'Psicólogo/a Organizacional',
    'Químico/a',
    'Secretario/a Ejecutivo/a',
    'Sociólogo/a',
    'Técnico/a de Laboratorio',
    'Terapeuta Ocupacional',
    'Traductor/a de Idiomas',
    'Veterinario/a',
    'Vendedor/a de Bienes Raíces',
    'Vendedor/a de Tecnología',
    'Zoólogo/a',
    'Otro',
  ];
