// Definir las opciones para los selects
export const Roles: string[] = [
  'Analista de Admisión de Créditos',
  'Analista de Contabilidad',
  'Analista de Créditos',
  'Analista de Desarrollo y Mantenimiento de Sistemas',
  'Analista de Infraestructura y Soporte Técnico',
  'Analista de Riesgo Crediticio',
  'Analista de Riesgo de Liquidez y Mercado',
  'Analista de Riesgo Operacional, Seguridad de la Información y Continuidad de Negocio',
  'Asistente Administrativo',
  'Asistente Central de Operaciones',
  'Asistente de Adquisiciones',
  'Asistente de Ahorros y Membresía',
  'Asistente de Almacén y Archivo',
  'Asistente de Atención al Usuario',
  'Asistente de Bienestar Social',
  'Asistente de Caja y Operaciones',
  'Asistente de Contabilidad',
  'Asistente de Créditos',
  'Asistente de Gerencia',
  'Asistente de Imagen Institucional y Relaciones Publicas',
  'Asistente de LA/FT',
  'Asistente de Marketing',
  'Asistente de Organización y Métodos',
  'Asistente de Planificación',
  'Asistente de Reclutamiento y Capacitación',
  'Asistente de Remuneraciones y Estadística',
  'Auxiliar de Logística',
  'Auxiliar de Operaciones',
  'Auxiliar de Servicios Generales',
  'Auxiliar de Trámite Administrativo',
  'Coordinador Administrativo',
  'Coordinador Contable',
  'Coordinador de Créditos',
  'Coordinador de Procesos Internos',
  'Coordinador Judicial',
  'Coordinador Procesal',
  'Gerente de Administración',
  'Gerente de Negocios',
  'Gerente de Operaciones y Finanzas',
  'Gerente de Riesgos',
  'Jefe de Asesoría Legal',
  'Jefe de Cobranzas',
  'Jefe de Contabilidad',
  'Jefe de Finanzas y Tesorería',
  'Jefe de Gestión del Talento Humano',
  'Jefe de Gobernanza Cooperativa',
  'Jefe de Inteligencia de Negocios',
  'Jefe de Logística',
  'Jefe de Marketing',
  'Jefe de Planificación y Métodos',
  'Jefe de Supervisión y Seguimiento',
  'Jefe de Tecnologías de la Información',
  'Jefe de Créditos',
  'Jefe de Planificación y Métodos',
  'Jefe de Seguridad',
  'Jefe Zonal',
  'Oficial de Cumplimiento',
  'Supervisor Zonal',
  // Agrega más roles según sea necesario
].sort();
